questions:
  - What's on your mind?
  - What can I help you with?
  - You have any questions? Ask away!
  - What's troubling you?
answers:
  - What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it. Don't complain.
  - Never miss a good chance to shut up.
  - Those who win never give up. Those who give up never win.
  - Trust the wait. Embrace the uncertainty. Enjoy the beauty of becoming. When nothing is certain, anything is possible.
  - Nothing is what one thinks it is. Cloth is stone and circus is an art. There are no certainties.
  - What had happened is unfortunate, what is going to happen is uncertain.
  - You have to find what sparks a light in you so that you in your own way can illuminate the world.
  - What defines you isn't how many times you crash but the number of times you get back.
  - You can be impatient and get fewer results or you can be patient and enjoy more than you desired. The choice is totally yours.
  - Impatience makes even the strong weak.
  - Being in a hurry does not slow down time.
  - A fear of weakness only strengthens weakness.
  - A humble man will always receive the best that others have to offer; for he recognizes the truth.
  - You never really learn much from hearing yourself speak.
  - There is only one thing that makes a dream impossible to achieve, the fear of failure.
  - Only those who dare to fail greatly can ever achieve greatly.